[project]
name = "ait-dsn"
version = "0.1.0"
requires-python = ">=3.7,<3.11"
dependencies = [
    "ait-core",
]

[tool.uv.sources]
ait-core = { git = "https://github.com/NASA-AMMOS/AIT-Core", rev = "2.5.2" }

[tool.ruff]
line-length = 320

[dependency-groups]
mayo = [
    "snakeviz>=2.2.0",
]
